# -*- coding: utf-8 -*-
"""2. Broad Overview Agent Discussion .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZoO1Y_xeHYPVUH7rcNMre5DnCTy94cDb

# Broadscale Overview of Fuel Delivery in Alaska

**2**. Broadscale overview of trends impacting fuel delivery in Alaska

Agents:
- Market Analyst -
- Delivery Method Analyst -
- Writing Agent -
- Contrarian Agent -

Goal: To assess the current market trends regarding bulk fuel facility sites in Alaska. This notebook will focus on doing current research on delivery methods, and cost of fuel transport in Alaska.

Input data:
- Structured JSON file of bulk fuel facility sites grouped into regions and delivery methods.
- Structured JSON file of broadscale recommendations from logistics coordinator in notebook #1

Pre-processing:
- 1. Regionalization Notebook (pre processing of data)

Outputs:
- A formatted report on current fuel trends in Alaska
"""

#Installations are handled in installations.txt file

#@title Import necessary libraries
import os
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)
from crewai import Agent, Task, Crew, LLM, Process
from crewai.tools import tool
from dotenv import load_dotenv
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import matplotlib.pyplot as plt
import numpy as np
import itertools, random, functools, time, json, math
from collections import Counter, defaultdict, namedtuple
from typing import Set, List, Tuple, Iterable, Callable, Dict
import pipeline
import pydantic


#Setting Working Directory
pipeline.set_cwd('/media/volume/Preliminary_mas_runs')

#Set up Agents
def setup_agents(llm, input_data, input_report):

    # Setting up Delivery Method Analyst
    delivery_analyst = Agent(
        role="Delivery Method Analyst",
        goal="Analyze fuel delivery methods and their relation to location within each Alaska Energy Development Region, considering the groupings in the provided data.",
        backstory="Expert in logistics and market analysis, with a focus on regional fuel delivery in Alaska.",
        verbose=True,
        llm=llm
    )

    delivery_task = Task(
        description=f"""
        Analyze the fuel delivery methods used for the facilities within each Alaska Energy Development Region, based on the {input_data} that has been regionalized and processed by delivery methods.
        The {input_data} has the following structure:
        Input format:
        {{'Region': North Slope {{'DeliveryMethod': Plane {{'site_id': 815 {{'Longitude': '-149.640262','Latitude': '61.269243'}} }} }} }}

        Use the {input_report} as your baseline, broadscale analysis.
        The input report was loaded in the previous notebook as a JSON format.
        The format of the input report is as follows:
        {{
            'overall_assessment': {{
                'Road - Railbelt': {{'status': 'Looks Good', 'reasoning': '...'}},
                'Plane - North Slope': {{'status': 'May Need Review', 'reasoning': '...'}}
                }},
            'key_recommendations': [
                'Recommendation 1',
                'Recommendation 2'],
            'summary: {{
                'practical_groupings': 5,
               'needs_adjustments': 2,
                'confidence_level': 'High'}}
        }}


        For each region:
        1. Describe the primary delivery methods observed for the facilities in that region.
        2. Analyze how the delivery methods relate to the geographical characteristics of the region (e.g., coastal vs. inland, road access).
        3. Consider the groupings generated by the regionalized input data for the facilities in this region. How do the identified delivery methods align with or diverge from the region?
        4. Identify potential logistical challenges and constraints specific to the delivery methods and geography of each region.

        Present your findings in a clear, narrative style, providing insights for each region based on the input data. Avoid returning the information in a JSON format.
        """,
        agent=delivery_analyst,
        expected_output="An objective analysis of delivery methods for each region, describing their relation to geography, alignment with input data routes, and regional logistical considerations."
    )

    #Setting up Research  Agent
    researcher = Agent(
        role="Research Analyst",
        goal="Find and analyze the latest information on a specific topic",
        backstory="You're an expert researcher with years of experience analyzing data",
        verbose=True,
        llm=llm
    )

    research_task = Task(
        description='''Research up to date fuel delivery challenges in Alaska.
        Consider challenges in different regions and the delivery methods that are the most logisitcally challenging.
        Find examples of real fuel delivery struggles that have occurred in Alaska.''',
        agent=researcher,
        expected_output= "A comprehensive notes page on fuel delivery challenges in Alaska"
    )

    # Setting up the Market Analysis Agent
    market_analyst = Agent(
        role = "Market Analyst",
        goal = "Analyze market dynamics, including fuel sources, demand, and economic factors in Alaska.",
        backstory = "Expert in market analysis and economics, specialized in Alaska economics.",
        verbose = True,
        llm = llm
    )

    market_task = Task(
        description = '''Analyze market trends regarding fuel in Alaska. Identify current and key market drivers.
        Assess the impact of potential changes to current fuel type and fuel delivery methods (e.g., pipeline expansion, alternate fuels).''',
        agent = market_analyst,
        expected_output = "A comprehensive market analysis report."
    )

    #Setting up Writing Agent
    writing_agent = Agent(
        role = "Fuel Delivery Analyst and Report Writer",
        goal = '''Write an engaging report that includes analysis and provides actionable recommendations for fuel delivery industry leaders in Alaska.
        This report should consider the input data that was analyzed by other agents. This data provides real data from bulk fuel facilities broken up into region and delivery methods.''',
        backstory = "You are an expert in fuel delivery economics, policy, logistics, and technical writing. You are skilled at analyzing complex information and presenting it in a clear, actionable format.",
        verbose = True,
        #tools=[save_json],
        llm = llm
    )

    #Multi-Agent Discussion Task
    multi_agent_discussion_task = Task(
        description = f"""
        The Delivery Analyst, Market Analyst, and you (Fuel Delivery Analyst and Report Writer) will have a discussion to inform the final report.

        * Delivery Analyst:
            * Share your analysis of fuel delivery methods and their relation to location in Alaska based in the {input_data} ang the broadscale analysis in the {input_report}.
            * Provide details about clusters of fuel tank locations, their characteristics (e.g., geographical extent, density, common delivery method), and specific examples of logistical challenges and constraints for each cluster.
            * For each cluster, discuss the advantages and disadvantages of the primary delivery methods, considering factors like cost, efficiency, and reliability.

        * Market Analyst:
            * Share your analysis of market dynamics, including fuel sources, demand, and economic factors in Alaska's fuel delivery market.
            * Provide specific examples of how these factors (e.g., pipeline capacity, price volatility, government regulations) influence fuel costs and delivery logistics in different regions of Alaska.
            * Discuss potential future market trends and their potential impact on fuel delivery strategies.

        * You (Fuel Delivery Analyst and Report Writer):
            * Synthesize the information from the Delivery Analyst and Market Analyst.
            * Identify the key points that should be included in the final report to provide a comprehensive understanding of the fuel delivery situation in Alaska.
            * Ask clarifying questions to all agents to ensure you have a complete understanding of the logistical challenges, market dynamics, and their interdependencies.
            * For example, ask about:
                * How do market fluctuations impact the different delivery methods in specific regions?
                * What are the most significant logistical bottlenecks that hinder efficient fuel delivery, and how do they vary across different regions?
                * What are the potential synergies or conflicts between different delivery methods, and how can they be optimized to improve overall efficiency?

        The goal of this discussion is to gather specific, actionable insights that will inform the recommendations in the final report.""",
        agent = writing_agent,
        expected_output = "A structured summary of the discussion, highlighting key points, added sections, specific examples, and actionable insights from each agent, and identifying what to include in the report."
    )

    #Setting up Contrarian Agent
    contrarian_agent = Agent(
        role = "Supply Chain and Logistics Contrarian",
        goal = "Critically evaluate the analysis and recommendations of other agents, identifying logical inconsistencies and potential oversights from a supply chain and logistics perspective.",
        backstory = "You are a seasoned supply chain and logistics expert with a contrarian mindset. You excel at identifying flaws in reasoning and finding alternative explanations.",
        verbose = True,
        llm = llm
    )

    contrarian_task = Task(
        description = """
        Critically review the comprehensive report and recommendations generated by the delivery_analyst, researcher, and market_analyst.
        From a supply chain management and logistics perspective, identify:

        1.  Any logical inconsistencies or contradictions in the analysis.
        2.  Potential oversights or missing considerations.
        3.  Alternative explanations or perspectives.
        4.  Any unrealistic or impractical recommendations.
        5.  Areas where the analysis could be strengthened with additional data or insights from supply chain and logistics domain.

        Present your findings in a structured text format, highlighting the specific areas of concern and providing alternative viewpoints or suggestions for improvement.
        Ensure your analysis is grounded in sound supply chain and logistics principles.
        """,
        agent = contrarian_agent,
        expected_output = "A structured text document containing a critical review of the combined_agent's report and recommendations."
    )

    #Contrarian & Writing Agent Discussion + Final Report Writing
    writing_discussion_task_2 = Task(
        description = """
        Review the critique provided by the contrarian_agent in contrarian_task.
        Respond to each point, providing justifications for your analysis and recommendations.
        Address any concerns raised by the contrarian_agent and propose revisions or alternative approaches if necessary.
        """,
        agent = writing_agent,
        expected_output = "A response to the contrarian_agent's critique, with justifications and revisions."
    )

    contrarian_discussion_task_3 = Task(
        description = """
        Review the writing_agent's response.
        Provide any follow-up critiques, or state that the writing_agent has sufficiently addressed the concerns.
        """,
        agent = contrarian_agent,
        expected_output = "Follow-up critiques or confirmation that the writing_agent has addressed concerns."
    )

    # Final Report Task
    writing_task = Task(
        description = """
        Based on the previous discussion with the contrarian_agent, the discussion with the Delivery Analyst, Market Analyst, and yourself, and the original analysis, produce a comprehensive document in plain text format that includes:

        1.  An engaging report that synthesizes the information from all relevant agents, highlighting the challenges and opportunities in fuel delivery in Alaska. Use essay-style writing to create a cohesive narrative.
        2.  A section containing clear and actionable recommendations for fuel delivery industry leaders on improving efficiency. These recommendations should be supported by the information presented in the report, especially the delivery method and market considerations.
        3.  Present the recommendations in a structured text format, focusing on key points and practical implementation.
        4.  A section titled "Agent Discussion Summary" that summarizes the key points, specific examples, and actionable insights from the discussion between the Delivery Analyst, Market Analyst, and yourself.  This section should clearly articulate how the discussion informed the final report's analysis and recommendations.
        5.  A section titled "Limitations" that includes a summary the contrarian_agent critiques, including the initial critique, the writing_agent's response, and any follow-up points.

        The final output should be a single document in JSON format that seamlessly integrates the report, the recommendations, and the contrarian agent's review.
        Use the 'save_json' tool to do this. The JSON should have the following structure:

        {{
        "title": "Comprehensive Alaska Fuel Delivery Analysis",
        "executive_summary": "Brief overview of key findings and recommendations (2-3 paragraphs)",
        "main_report": {{
            "introduction": "Engaging narrative introducing Alaska fuel delivery challenges",
            "challenges": "Essay-style discussion of primary challenges",
            "opportunities": "Essay-style discussion of key opportunities",
            "delivery_methods_analysis": "Analysis of each delivery method",
            "market_considerations": "Market dynamics and regional considerations",
            "conclusion": "Synthesis of findings"}},

        "recommendations": {{
            "strategic_priorities": [
                {{"priority": "Priority name", "description": "Detailed description",
                    "implementation_steps": ["Step 1", "Step 2"], "expected_impact": "Expected outcome",
                    "supporting_evidence": "Reference to report findings"}}],
            "operational_improvements": [
                {{ "improvement": "Improvement name", "description": "Detailed description",
                "implementation_steps": ["Step 1", "Step 2"],"expected_impact": "Expected outcome"}}],

        "agent_discussion_summary": {{
            "overview": "How the multi-agent discussion shaped the analysis",
            "delivery_analyst_insights": ["Key insight 1", "Key insight 2"],
            "market_analyst_insights": ["Key insight 1", "Key insight 2"],
            "synthesis_insights": ["How insights were integrated", "Cross-functional considerations"],
            "impact_on_recommendations": "How the discussion influenced final recommendations"}},

        "limitations": {{
            "contrarian_critique_initial": "Summary of initial critique from contrarian_agent",
            "response_to_critique": "How the writing_agent addressed the concerns",
            "follow_up_points": ["Follow-up point 1", "Follow-up point 2"],
            "acknowledged_limitations": ["Limitation 1", "Limitation 2"],
            "areas_for_further_research": ["Research area 1", "Research area 2"]}},

        "metadata": {{
            "date_generated": "YYYY-MM-DD",
            "agents_involved": ["Delivery Analyst", "Market Analyst", "Contrarian Agent", "Writing Agent"],
            "data_sources": ["Source 1", "Source 2"],
            "confidence_level": "High/Medium/Low"}}
        }}""",
        agent = writing_agent,
        expected_output = '''A comprehensive document in JSON format containing an engaging report,
        actionable recommendations, and the contrarian agent's critical review.'''
    )
    return (delivery_analyst, delivery_task, 
        researcher, research_task, 
        market_analyst, market_task,
        writing_agent, multi_agent_discussion_task,
        contrarian_agent, contrarian_task,
        writing_discussion_task_2, contrarian_discussion_task_3, 
        writing_task)

@tool("save_json")
def save_json(json_report: str):
  '''Function to save the final assessment report as a JSON file.

    Args:
        json_report (str): A JSON string containing the assessment report with keys:
            - '''
  with open('final_report.json', 'w') as f:
    json.dump(json_report, f, indent=4)


# Main Crew set up & main code

def main():
    #Set LLM and API Key
    with open('.env', 'w', encoding='utf-8') as f:
        f.write(f"GEMINI_API_KEY={pipeline.get_api_key()}\n")
        f.write("MODEL=gemini/gemini-2.5-flash-preview-04-17\n")
    
    load_dotenv()
    os.environ["GEMINI_API_KEY"] = pipeline.get_api_key()
    llm = LLM(model='gemini/gemini-2.5-flash')
    
    # Acquire and read in data into a dictionary
    input_json = 'output_regionalization_dictionary.json'
    with open(input_json, 'r') as file:
        input_data = json.load(file)
    
    input_report = 'logistics_report.json'
    with open(input_report, 'r') as file:
        input_report = json.load(file)
    
    # Unpack the agents and tasks returned by setup_agents
    delivery_analyst, delivery_task, \
    researcher, research_task, \
    market_analyst, market_task, \
    writing_agent, multi_agent_discussion_task, \
    contrarian_agent, contrarian_task, \
    writing_discussion_task_2, contrarian_discussion_task_3, \
    writing_task = setup_agents(llm, input_data, input_report)

    # Set up CrewAI
    crew = Crew(
        agents=[delivery_analyst, researcher, market_analyst, contrarian_agent, writing_agent],
        tasks=[delivery_task, research_task, market_task, multi_agent_discussion_task, 
               writing_discussion_task_2, contrarian_discussion_task_3, writing_task],
        process=Process.sequential,
        verbose=True,
        llm=llm
    )
    
    print("Running CrewAI approach...")
    
    # Pass results to CrewAI agents
    result = crew.kickoff()
    
    # Print the result directly instead of trying to convert to JSON
    print(result)
    
    with open('final_report.json', 'w', encoding='utf-8') as f:
        json.dump({"result": str(result)}, f, indent=4)

if __name__ == "__main__":
    main()

