# -*- coding: utf-8 -*-
"""1. Regionalization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O3i5XODO7GGtl3wjTNm0AdkJwlf537Vz

# Regional Logistics Coordinator

Goal: To create a dictionary of bulk fuel facility sites and group each site into a pre-determined region. This will be fed into the successive agentic frameworks

Input data:
- Bulk Fuel Facility Sites (csv)
- Alaska Energy Development Regions (shapefile)

Pre-processing:
- Groups sites by region
- Groups sites by delivery method within each region

Agents:
- Delivery Method Coordinator: Using the pre-processed data, this agent assigned delivery methods to sites without a delivery method based on surrounding sites
- Logistics Coordinator: Runs a basic high-level assessment of route risks (length, geography considerations etc)

Outputs:
- A grouped dictionary with lat, long, delivery method and region of each bulk fuel facility site in Alaska
- A formatted report on the preliminary risk assessments of current routes
"""

#@title Install CrewAI and other libraries
#Installations are handled in installations.txt file

#@title Imports

import os
import crewai
from google.colab import userdata
from crewai import Agent, Task, Crew, LLM, Process
from crewai.tools import tool
from dotenv import load_dotenv
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import matplotlib.pyplot as plt
import json
from typing_extensions import final
import pipeline

#Setting Working Directory
pipeline.set_cwd('/media/volume/GraphDB_Runs')

#@title Retrieving Data
bulk_fuel_data = pd.read_csv('Utilities_Bulk_Fuel_Inventory.csv', usecols =['ASTFacilityID','ASTFacilityLongitude', 'ASTFacilityLatitude']) # Bulk fuel facility sites
regional_data = gpd.read_file('Alaska_Energy_Authority_Library.shp') #Regional Data
bulk_fuel_csv_path = 'Utilities_Bulk_Fuel_Inventory.csv'
shapefile_path = 'Alaska_Energy_Authority_Library.shp'

# globals
global final_regionalized_dict
global bulk_fuel_dict_with_regions
global unassigned_dict
final_regionalized_dict = {}
bulk_fuel_dict_with_regions = {}
unassigned_dict = {}

#@title Functions to parse data

def group_sites_by_region(bulk_fuel_csv_path: str, shapefile_path: str, region_column: str = "NAME") -> str:

    """ Takes bulk fuel facility data and Alaska regional shapefile, performs spatial join,
    and returns a dictionary mapping each facility to its region.

    Parameters:
        bulk_fuel_csv_path: Path to the CSV file containing bulk fuel facility data
        shapefile_path: Path to the Alaska Energy Development Regions shapefile
        region_column: Name of the region column in the shapefile (default: None)

    Return: Two formatted dictionaries - bulk_fuel_dict_with_regions and unassigned_dict """

    # Process input data
    bulk_fuel_data = pd.read_csv(bulk_fuel_csv_path, usecols =['ASTFacilityID','ASTFacilityLongitude', 'ASTFacilityLatitude', 'Delivery_method']) # Bulk fuel facility sites
    regional_shapefile = gpd.read_file(shapefile_path)                                                                                            # Regional Shapefile
    bulk_fuel_data = bulk_fuel_data.dropna(axis=0, how='all', subset=['ASTFacilityLongitude', 'ASTFacilityLatitude'])                             # Drop rows with missing coordinates

    # Convert site coordinates to Point geometries
    geometry = [Point(xy) for xy in zip(bulk_fuel_data['ASTFacilityLongitude'],bulk_fuel_data['ASTFacilityLatitude'])]

    # Create a GeoDataFrame from sites
    bulk_fuel_sites_gdf = gpd.GeoDataFrame(bulk_fuel_data, geometry=geometry)
    bulk_fuel_sites_gdf.set_crs(epsg=4326, inplace=True)                  ######## Could change crs here!!

    # Check and align CRS
    if bulk_fuel_sites_gdf.crs != regional_shapefile.crs:
        bulk_fuel_sites_gdf = bulk_fuel_sites_gdf.to_crs(regional_shapefile.crs)

    # Perform spatial join - finds which region each site falls into
    # how ='left' will keep all sites even if they are not assigned a region
    # predicate = 'within' checks if points are within the polygons
    sites_with_regions = gpd.sjoin(bulk_fuel_sites_gdf,regional_shapefile,how='left',predicate='within')

    # Assigning regions to each site
    for index, row in sites_with_regions.iterrows():
        facility_id = row['ASTFacilityID'] # Get facility ID
        region_value = row.get(region_column, None) # Get region value
        # Convert region from NaN to None, if needed
        if pd.isna(region_value):
            region_value = None
            unassigned_dict[facility_id]={ # Add to unassigned dictionary
                'FacilityID': facility_id,
                'Longitude': row['ASTFacilityLongitude'],
                'Latitude': row['ASTFacilityLatitude'],
                'Delivery_method': row['Delivery_method'],
                'Region': 'Unassigned'
            }
        else:  # Adds all sites with a set region
          bulk_fuel_dict_with_regions[facility_id] = {
              'FacilityID': facility_id,
              'Longitude': row['ASTFacilityLongitude'],
              'Latitude': row['ASTFacilityLatitude'],
              'Delivery_method': row['Delivery_method'],
              'Region': region_value}


    # Save to CSV in current working directory
    result_df = pd.DataFrame(sites_with_regions.drop(columns='geometry'))
    result_df.to_csv('sites_with_regions.csv', index=False)

    # Calculate statistics
    total_sites = len(bulk_fuel_dict_with_regions)
    sites_with_region = sum(1 for v in bulk_fuel_dict_with_regions.values() if v['Region'] is not None)
    sites_without_region = total_sites - sites_with_region

    # Return summary statistics
    summary = f"""
    Regionalization Complete!

    Total Facilities: {total_sites}
    Facilities Assigned to Regions: {sites_with_region}
    Facilities Without Region Assignment: {sites_without_region}

    Results saved to 'sites_with_regions.csv'

    """

    print(summary)
    # Return global dictionaries
    return bulk_fuel_dict_with_regions, unassigned_dict


def get_region_statistics(csv_path: str = 'sites_with_regions.csv') -> str:
    """
    Analyzes the regionalization results and provides statistics by region.
    Parameters:
        csv_path: Path to the CSV file with region assignments
    Return: String with regional statistics
    """
    df = pd.read_csv(csv_path)

    # Count facilities per region
    region_counts = df.groupby('NAME').size().sort_values(ascending=False)

    stats = "Facilities per Region:\n"
    for region, count in region_counts.items():
        stats += f"{region}: {count} facilities\n"

    return stats

def structure_regional_dictionaries (bulk_fuel_dict_with_regions: dict):
    '''Function to create a regional nested dictionary for each region in Alaska'''

    temp_regional_dict = {} # Create an overall dictionary to store sites by region
    # Accesses each bulk fuel facility site using the facility_id
    for facility_id, data in bulk_fuel_dict_with_regions.items():
        region = data.get('Region')
        if region is None:
          continue
        if region not in temp_regional_dict:        # Create region key if it doesn't exist
          temp_regional_dict[region] = {}           # Initiates new dictionary for a region
        temp_regional_dict[region][facility_id] = { # Add facility to this region's dictionary
          'FacilityID': facility_id,
          'Longitude': data['Longitude'],
          'Latitude': data['Latitude'],
          'Delivery_method': data['Delivery_method']}

    return temp_regional_dict

def plot_by_regions(reg_dict: dict, unassigned_dict: dict):
  ''' Function to plot by regions, using separate colors'''
  # Create a figure and axis
  fig, ax = plt.subplots(figsize=(10, 10))

  colors = ['#e6194B','#3cb44b','#ffe119','#4363d8','#f58231','#911eb4','#42d4f4','#f032e6','#bfef45','#fabed4','#469990','#dcbeff','#9A6324','#808000']

  # Plot each region with a different color
  for region, sites in reg_dict.items():
      x = [site['Longitude'] for site in sites.values()]
      y = [site['Latitude'] for site in sites.values()]
      ax.scatter(x, y, color=colors.pop(), label=region)

  # Plot unassigned sites (fixed the iteration)
  if unassigned_dict:  # Only plot if there are unassigned sites
      x = [site['Longitude'] for site in unassigned_dict.values()]
      y = [site['Latitude'] for site in unassigned_dict.values()]
      ax.scatter(x, y, color='black', label='Unassigned', s=30, marker='x')

  # Set labels and title
  ax.set_xlabel('Longitude')
  ax.set_ylabel('Latitude')
  ax.set_title('Bulk Fuel Facilities by Region')
  #ax.legend()
  ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))

  # Show the plot
  plt.tight_layout()
  plt.show()

def group_by_delivery_method(regional_dict):
  '''Function to group sites by delivery method within each region'''
  #global regional_dict # Points to global variable
  global final_regionalized_dict
  temp_dict ={}
  for region, sites in regional_dict.items():
    for facility_id, data in sites.items():
      delivery_method = data.get('Delivery_method')
      if delivery_method is None:
        continue
      if region not in temp_dict:
        temp_dict[region] = {}
      if delivery_method not in temp_dict[region]:
        temp_dict[region][delivery_method] = {}
      if facility_id not in temp_dict[region][delivery_method]:
        temp_dict[region][delivery_method][facility_id] = {
          'Longitude': data['Longitude'],
          'Latitude': data['Latitude']}

  final_regionalized_dict = temp_dict # Set to global variable
  return final_regionalized_dict

@tool("add_new_delivery_methods")
def add_new_delivery_methods():
  '''Function to add delivery methods to the regionalized dictionary'''
  global final_regionalized_dict
  for region in final_regionalized_dict.items():
    for methods in region.items():
      for facilities in methods.items():
        if facility_id in facilities:
          if delivery_method == methods:
            print("Already has correct delivery method.")
            continue
          else:
            facilities.remove(facility_id) # Remove from old grouping in the dictionary
            print(f"  Removed {facility_id} from {methods} in {region}")
            # Add to new delivery method
            if delivery_method not in final_regionalized_dict[region]:
              final_regionalized_dict[region][delivery_method] = []
            final_regionalized_dict[region][delivery_method].append(facility_id)
            print(f"Added {facility_id} to {delivery_method} in {region}")
    return final_regionalized_dict
@tool("get_facility_dictionary")
def get_facility_dictionary() -> str:
    """Retrieves the complete facility dictionary with all site information"""
    return json.dumps(final_regionalized_dict, indent=2)

@tool("update_facility_dictionary")
def update_facility_dictionary(new_dict: str) -> str:
    """Updates the facility dictionary with new data"""
    global final_regionalized_dict
    final_regionalized_dict = json.loads(new_dict)
    return "Dictionary updated successfully"

@tool("save_json")
def save_json(json_report: str):
  '''Function to save the logistics assessment report as a JSON file.

    Args:
        json_report (str): A JSON string containing the assessment report with keys:
            - overall_assessment: dict with grouping evaluations
            - key_recommendations: list of recommendations
            - summary: dict with summary statistics'''
  with open('logistics_report.json', 'w') as f:
    json.dump(json_report, f, indent=4)


def save_as_csv():
  '''Function to save the 'final_regionalized_dict' as a csv file
  in a correct format in the current working directory.'''

  global final_regionalized_dict # Access the dictionary from global scope
  rows = []  # Create rows list
  # Loop through dictionary to capture each sites and its data
  for region, delivery_methods in final_regionalized_dict.items():
    for delivery_method, facilities in delivery_methods.items():
      for facility_id, data in facilities.items():
          rows.append({
               'Region': region,
               'Delivery_method': delivery_method,
               'Facility_id': facility_id,
               'Longitude': data['Longitude'],
               'Latitude': data['Latitude']})
  final_df = pd.DataFrame(rows)
  final_df.to_csv('regionalized_df.csv', index=False)
  return final_df

# --------------------------------------------------------------------------------
#@title Set up Agents

#Set LLM and API Key
with open('.env', 'w', encoding='utf-8') as f:
  f.write(f"GEMINI_API_KEY={pipeline.get_api_key()}\n")
  f.write("MODEL=gemini/gemini-2.5-flash-preview-04-17\n")

load_dotenv()
os.environ["GEMINI_API_KEY"] = pipeline.get_api_key()
llm=LLM(model='gemini/gemini-2.5-flash')
# --------------------------------------------------------------------------------


# Agent - Delivery method analyst
delivery_method_agent = Agent(
    role="Delivery Method Coordinator",
    goal="Analyze each bulk fuel facility site's delivery method to ensure each has a set delivery method.",
    backstory="""Expert in logistics and market analysis, with a focus on regional fuel delivery in Alaska, specifcally delivey methods.""",
    verbose=True,
    llm=llm,
    tools=[add_new_delivery_methods, get_facility_dictionary,update_facility_dictionary])

delivery_task = Task(
    description=f"""
    Use the get_facility_dictionary tool to retrieve the current facility data.

    Complete the following tasks:
    1. Analyze the dictionary to ensure each site has a delivery method specified.
        a. If sites do not have a specified delivery method:
          - Examine delivery methods used by other facilities in the same region
          - Assign the most common delivery method from that region
          - If the region has mixed methods, assign based on geographic proximity patterns
          - With the facility ID and delivery method, add to the dictionary using add_new_delivery_methods tool.
        b. If sites have multiple delivery methods (e.g., 'Plane or Road'):
          - Keep these sites and groupings as is.
  2. Once complete, return the dictionary in the same format as the input dictionary using the update_facility_dictionary tool""",
    agent = delivery_method_agent,
    expected_output=
    '''In JSON format:
    - The complete modified dictionary with all delivery methods assigned
    - Summary of each newly added delivery method (if no delivery method was present).
    - Summary of sights that have more than 1 delivery method.''',
    verbose=True)

# Agent - Logistics Coordinator
logistics_agent = Agent(
    role="Logistics Coordinator",
    goal="Provide a high-level assessment of whether each route grouping is realistic and practical for Alaska fuel delivery operations.",
    backstory='''Expert in Alaska's geography and logistics with practical experience in fuel delivery
    operations. Knows the general operational limits of road, plane, and barge delivery methods in Alaska's
    unique environment. Provides straightforward assessments of whether route groupings make practical sense
    based on distance, geography, and delivery method capabilities.''',
    verbose=True,
    llm=llm,
    tools=[save_json])

logistics_task = Task(
    description=f"""
    Review the updated dictionary provided in the previous task:{final_regionalized_dict}

    For each grouping (e.g., 'Road - Railbelt', 'Plane - North Slope'),
    provide a general assessment of whether the grouping is realistic and practical.

    Consider:
    - Is the geographic area too large for a single route with this delivery method?
    - Does the delivery method make sense for the distances and terrain involved?
    - Are there obvious geographic or logistical issues that would make this grouping impractical?

    Keep the assessment general and straightforward - focus on obvious concerns rather than
    detailed logistics planning. Flag groupings that seem problematic and suggest simple
    improvements where needed.

    Structure your response as a valid JSON object, then use the 'save_json' tool
    to save it. Pass your complete JSON object (as a string) to the save_json tool.""",
    agent = logistics_agent,
    context = [delivery_task], # Pass JSON to logistics coordinator
    expected_output = """
    A concise assessment report containing:

    1. Overall Assessment:
       - Brief evaluation of each delivery_method-region grouping
       - Simple status for each: "Looks Good", "May Need Review", or "Likely Too Large"
       - High-level reasoning for any concerns

    2. Key Recommendations:
       - List groupings that appear unrealistic or too broad
       - General suggestions for improvement (e.g., "Consider splitting this region into 2-3 smaller areas")
       - Any obvious mismatches between delivery method and geography

    3. Summary:
       - How many groupings seem practical?
       - How many may need adjustments?
       - General confidence level in the current grouping structure

    Format: In a JSON format create a clear, readable summary focusing on practical applicability rather than detailed logistics.

    A JSON object with this exact structure:
    {{
        "overall_assessment": {{
            "Road - Railbelt": {{"status": "Looks Good", "reasoning": "..."}},
            "Plane - North Slope": {{"status": "May Need Review", "reasoning": "..."}}
        }},
        "key_recommendations": [
            "Recommendation 1",
            "Recommendation 2"
        ],
        "summary": {{
            "practical_groupings": 5,
            "needs_adjustments": 2,
            "confidence_level": "High"
        }}
    }}""",
    verbose=True)

#@title Setting up main function to execute the crewAI

def run_regionalization(bulk_fuel_csv_path: str, shapefile_path: str, region_column: str = None):
    """Execute the CrewAI workflow to regionalize bulk fuel facilities.

    Parameters:
        bulk_fuel_csv_path: Path to bulk fuel facility CSV
        shapefile_path: Path to Alaska regions shapefile
        region_column: Column name for region in shapefile

    Return: Dictionary with facility assignments"""

    group_sites_by_region(bulk_fuel_csv_path, shapefile_path, region_column)      # Group sites by region using shapefile and XY coordinates
    regional_dict = structure_regional_dictionaries(bulk_fuel_dict_with_regions)  # Create a structured regional dictionary
    plot_by_regions(regional_dict, unassigned_dict)                               # Plot sites by region, including unassigned facilities
    final_regionalized_dict = group_by_delivery_method(regional_dict)             # Group by delivery method within each region

    print("Running CrewAI approach...")
    print("="*50)
    # Sets up crewAI
    crew = Crew(
        agents=[delivery_method_agent,logistics_agent],
        tasks=[delivery_task,logistics_task],
        process=Process.sequential,
        verbose=True)

    # Run the crew
    result = crew.kickoff(inputs={'final_regionalized_dict': final_regionalized_dict}) # Pass path as string

    # Print statements
    print("\n" + "="*50)
    print("CREW EXECUTION COMPLETE")
    print("="*50)
    print(result)

    # Return the dictionary that was stored globally by the tool
    return final_regionalized_dict

# Main Function call
def main():
    region_column = 'NAME'
    run_regionalization(bulk_fuel_csv_path, shapefile_path, region_column)
    # Write output dictionary to a json formatted file
    with open("output_regionalization_dictionary.json", "w") as outfile:
        # Convert the dictionary to a JSON string before writing
        outfile.write(json.dumps(final_regionalized_dict, indent=4))
    save_as_csv() # Save as csv output file

if __name__ == "__main__":
    main()



