# -*- coding: utf-8 -*-
"""3. TSP model .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-KlKhq4K9WXY3Z1wMqkr2E6I-nltSim

# A Multi-Agent System for Regionalized Fuel Delivery (TSP - route settting)

**3**. TRAVELING SALESPERSON Notebook

Agents:
- Traveling Salesperson (TSP)
- Cost Estimator Agent
- Operational Risk Agent
- Writing Agent
- Contrarian Agent

Goal: To calculate optimal route for fuel delivery in Alaska according to region and delivery method groupings.

Input data:
- Structured JSON dictionary of bulk fuel facility sites grouped into regions and delivery methods.
- Final report in a JSON format from Notebook #2

Pre-processing:
- 1. Regionalization Notebook (pre processing of data)
- 2. Initial analysis report from Notebook #2

Outputs:
- A map of routes across Alaska
- A formatted report of findings
"""
#Installations are handled in installations.txt file

#@title Import necessary libraries
import os
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)
from crewai import Agent, Task, Crew, LLM, Process
from crewai.tools import tool
from dotenv import load_dotenv
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import matplotlib.pyplot as plt
import numpy as np
import random, math, json, functools, time, itertools
from collections import Counter, defaultdict, namedtuple
from typing import Set, List, Tuple, Iterable, Callable, Dict
import pydantic
import pipeline


#Setting Working Directory
pipeline.set_cwd('/media/volume/GraphDB_Runs')

#@title Set globals & Retrieving Data
global input_dict
global tsp_regional_results_dict


# Set-Up Traveling Sales Person Algorithm --> Function to parse locations and delivery methods
def parse_regional_locations(input_dict: dict, region: str, del_method: str) -> Tuple[frozenset, dict, dict]:
  if region not in input_dict:
      raise ValueError(f"Region '{region}' not found in regional dictionary")
  region_data = input_dict[region]
  delivery_method_region = input_dict[region][del_method]
  group_cities = frozenset(complex(float(data['Longitude']), float(data['Latitude'])) for data in delivery_method_region.values())

  return group_cities, delivery_method_region

# TSP functions
City = complex
Cities = frozenset
Tour = list
TSP = callable
Link = Tuple[City, City]


def distance(A: City, B: City) -> float:
    '''Distance between two cities in miles. The starting values are in coordinates (latitude, longitude).
    This function uses the haversine formula to calculate the distance between two points on a sphere.
    Source: https://community.esri.com/t5/coordinate-reference-systems-blog/distance-on-a-sphere-the-haversine-formula/ba-p/902128'''

    lon1, lat1 = A.real, A.imag
    lon2, lat2 = B.real, B.imag

    R = 3959  # Earth's radius in miles

    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)

    a = math.sin(dlat/2)**2 + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon/2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    distance_miles = R * c

    return distance_miles


def shortest(tours: Iterable[Tour]) -> Tour:
    "The tour with the smallest tour length."
    return min(tours, key=tour_length)

def tour_length(tour: Tour) -> float:
    "The total distances of each link in the tour, including the link from last back to first."
    return sum(distance(tour[i], tour[i - 1]) for i in range(len(tour)))

def valid_tour(tour: Tour, cities: Cities) -> bool:
    "Does `tour` visit every city in `cities` exactly once?"
    return Counter(tour) == Counter(cities)

Segment = list

def plot_tour(tour: Tour, style='bo-', hilite='rs', title=''):
    "Plot every city and link in the tour, and highlight the start city."
    scale = 1 + len(tour) ** 0.5 // 10
    plt.figure(figsize=((3 * scale, 2 * scale)))
    start = tour[0]
    plot_segment([*tour, start], style)
    plot_segment([start], hilite)
    plt.title(title)

def Xs(cities) -> List[float]: "X coordinates"; return [c.real for c in cities]

def Ys(cities) -> List[float]: "Y coordinates"; return [c.imag for c in cities]

def plot_segment(segment: Segment, style='bo:', color=None):
    "Plot every city and link in the segment."
    if color is not None:
        plt.plot(Xs(segment), Ys(segment), style, linewidth=2/3, markersize=4, clip_on=False, color=color)
    else:
        plt.plot(Xs(segment), Ys(segment), style, linewidth=2/3, markersize=4, clip_on=False)
    plt.axis('scaled'); plt.axis('off')

def run(tsp: callable, cities: Cities):
    """Run a TSP algorithm on a set of cities and plot/print results."""
    t0 = time.perf_counter()
    tour = tsp(cities)
    t1 = time.perf_counter()
    L = tour_length(tour)
    print(f"length {round(L):,d} tour of {len(cities)} cities in {t1 - t0:.3f} secs")
    plot_tour(tour)

def possible_tours(cities) -> List[Tour]:
    "Return a list of non-redundant tours (permutations of cities with first city first)."
    start, *others = cities
    return [[start, *perm] for perm in itertools.permutations(others)]

def nearest_tsp(cities, start=None) -> Tour:
    """Create a partial tour that initially is just the start city.
    At each step extend the partial tour to the nearest unvisited neighbor
    of the last city in the partial tour, while there are unvisited cities remaining."""
    start = start or next(iter(cities))
    tour = [start]
    unvisited = set(cities) - {start}
    def extend_to(C): tour.append(C); unvisited.remove(C)
    while unvisited:
        extend_to(nearest_neighbor(tour[-1], unvisited))
    return tour

def first(collection):
    """The first element of a collection."""
    return next(iter(collection))

def nearest_neighbor(A: City, cities) -> City:
    """Find the city C in cities that is nearest to city A."""
    return min(cities, key=lambda C: distance(C, A))

def rep_nearest_tsp(cities, k=10):
    "Repeat nearest_tsp starting from k different cities; pick the shortest tour."
    return shortest(nearest_tsp(cities, start) for start in random.sample(list(cities), min(k, len(cities))))

def sample(population, n, seed=42) -> Iterable:
    "Return a list of n elements sampled from population. Set random.seed."
    random.seed((n, seed))
    return random.sample(population, min(n, len(population)))

def opt2(tour) -> Tour:
    "Perform 2-opt segment reversals to optimize tour."
    changed = False
    old_tour = list(tour)
    for (i, j) in subsegments(len(tour)):
        if reversal_is_improvement(tour, i, j):
            tour[i:j] = reversed(tour[i:j])
            changed = True
    return (tour if not changed else opt2(tour))

def reversal_is_improvement(tour, i, j) -> bool:
    "Would reversing the segment `tour[i:j]` make the tour shorter?"
    A, B, C, D = tour[i-1], tour[i], tour[j-1], tour[j % len(tour)]
    return distance(A, B) + distance(C, D) > distance(A, C) + distance(B, D)

cache = functools.lru_cache(None)

@cache
def subsegments(N) -> Tuple[Tuple[int, int]]:
    "Return (i, j) index pairs denoting tour[i:j] subsegments of a tour of length N."
    return tuple((i, i + length)
                 for length in reversed(range(2, N - 1))
                 for i in range(N - length))

class Result(namedtuple('_', 'tsp, opt, tour, cities, secs')):
    """A `Result` records the results of a `run` on a TSP."""
    def __repr__(self):
        best = min([tour_length(r.tour) for r in all_results[self.cities]], default=tour_length(self.tour))
        return (f"{name(self.tsp, self.opt):>25}: length {round(tour_length(self.tour)):,d} tour "
                f"({tour_length(self.tour)/best:5.1%}) in {self.secs:6.3f} secs")

class RegionalTourResult(namedtuple('_', 'region, tour, length, secs, num_sites')):
    """Result for a single region's TSP tour."""
    def __repr__(self):
        return (f"Region: {self.region:>20} | Sites: {self.num_sites:>3} | "
                f"Length: {round(self.length):>6,d} miles | Time: {self.secs:6.3f}s")

all_results = defaultdict(list)

def name(tsp, opt=None) -> str: return tsp.__name__ + (('+' + opt.__name__) if opt else '')

def run(tsp: TSP, cities: Cities, opt=None) -> Result:
    """Run a TSP algorithm on a set of cities and return results with segment distances."""
    if opt:
        res0 = run(tsp, cities, None)
        t0 = time.perf_counter()
        tour = opt(Tour(res0.tour))
        t1 = time.perf_counter()
        secs = res0.secs + t1 - t0
    else:
        t0 = time.perf_counter()
        tour = tsp(cities)
        t1 = time.perf_counter()
        secs = t1 - t0

    result = Result(tsp, opt, tour, cities, secs)
    all_results[cities].append(result)
    assert valid_tour(tour, cities)
    return result

def runs(tsps, cities, opts=(None, opt2)) -> List[Result]:
    """Run each of the tsps on the cities, and return a list of all results on `cities`."""
    for tsp, opt in itertools.product(tsps, opts):
        run(tsp, cities, opt)
    all_results[cities].sort(key=lambda r: tour_length(r.tour))
    best = all_results[cities][0]
    plot_tour(best.tour, title=repr(best))
    return all_results[cities]

def rep_opt2_nearest_tsp(cities, k=10) -> Tour:
    """Apply 2-opt to *each* of the repeated nearest neighbors tours."""
    return shortest(opt2(nearest_tsp(cities, start)) for start in sample(cities, k))

def greedy_tsp(cities):
    """Go through links, shortest first. If a link can join segments, do it."""
    endpoints = {C: [C] for C in cities}
    links = itertools.combinations(cities, 2)
    for (A, B) in sorted(links, key=lambda link: distance(*link)):
        if A in endpoints and B in endpoints and endpoints[A] != endpoints[B]:
            joined_segment = join_segments(endpoints, A, B)
            if len(joined_segment) == len(cities):
                return joined_segment

def shortest_links_first(cities) -> List[Link]:
    "Return all links between cities, sorted shortest first."
    return sorted(itertools.combinations(cities, 2), key=lambda link: distance(*link))

def join_segments(endpoints, A, B):
    "Join segments [...,A] + [B,...] into one segment. Maintain `endpoints`."
    Aseg, Bseg = endpoints[A], endpoints[B]
    if Aseg[-1] is not A: Aseg.reverse()
    if Bseg[0] is not B: Bseg.reverse()
    Aseg += Bseg
    del endpoints[A], endpoints[B]
    endpoints[Aseg[0]] = endpoints[Aseg[-1]] = Aseg
    return Aseg

def greedy_tsp_generator(cities) -> Iterable[List[List[City]]]:
    """Go through links, shortest first. If a link can join segments, do it.
    Yield a list of segments on each iteration."""
    endpoints = {C: [C] for C in cities}
    segments = []
    links = itertools.combinations(cities, 2)
    segment_count = len(cities)
    for (A, B) in sorted(links, key=lambda link: distance(*link)):
        if A in endpoints and B in endpoints and endpoints[A] != endpoints[B]:
            joined_segment = join_segments(endpoints, A, B)
            segments = list({tuple(s) for s in endpoints.values()})
            if len(segments) < segment_count:
                segment_count = len(segments)
                yield [list(s) for s in segments]
            if len(joined_segment) == len(cities):
                yield [list(s) for s in segments]
                return


def plot_regional_tours(input_dict: dict, results: dict):
    """Plot all regional tours on separate subplots."""

    num_regions = len(input_dict)  # Find number of regions

    if num_regions == 0: # Error handling (if structured results dictionary is empty)
        print("No regional tour results to plot.")
        return

    cols = min(3, num_regions) # Number of columns
    rows = (num_regions + cols - 1) // cols # Number of rows
    fig, axes = plt.subplots(rows, cols, figsize=(15*cols, 12*rows))

    if num_regions == 1:
        axes = [axes]
    else:
        axes = axes.flatten() if num_regions > 1 else [axes]

    # Load Alaska boundary (download natural earth data)
    try:
        # Load US states from natural earth data
        url = "https://www2.census.gov/geo/tiger/GENZ2018/shp/cb_2018_us_state_20m.zip"
        states = gpd.read_file(url)
        alaska = states[states['NAME'] == 'Alaska']
    except:
        alaska = None
        print("Could not load Alaska boundary")

    # Color palette
    cmap = plt.colormaps['tab10']

    #Plot each region on its own subplot
    for idx, (region, groups) in enumerate(sorted(results.items())):
      #print(f"Plotting {region}")
      ax = axes[idx]
      plt.sca(ax)

      #Plot Alaska boundary
      if alaska is not None:
          alaska.boundary.plot(ax=axes[idx], color='black', linewidth=0.5, zorder=0)

      #Find total sites per region and tours per region
      if region in results:
            total_sites = sum(results[region][group_name].num_sites for group_name in groups if group_name in results[region])
      # Create subplot title
      ax.set_title(f"{region}\n {total_sites} sites, {len(groups)} tours")

      legend_list = []
      for group_idx, group_name in enumerate(sorted(groups.keys())):
        print(f"Plotting {group_name}")

        #Get tour information
        tour = results[region][group_name].tour
        num_sites = results[region][group_name].num_sites
        length = results[region][group_name].length

        # Setting colors
        if group_name == 'NaN':
          color = 'black'
          ax.scatter(Xs(tour), Ys(tour), color=color, s=10, marker='x', label='Unknown Delivery Method')
          legend_label = f"Unknown Delivery Method: {num_sites} sites, {length:.1f} mi"
          legend_list.append(plt.Line2D([0], [0], color=color, marker='x', label=legend_label))
        else:
          if group_name == 'Road':
              color = 'orange'
          elif group_name == 'Plane':
              color = 'blue'
          elif group_name == 'Barge':
              color = 'green'
          elif group_name =='Plane or Road':
              color = 'purple'

          #Plotting the tour
          tour_with_return = [*tour, tour[0]]
          plot_segment(tour, style='o-', color=color)
          plot_segment([tour[0]], style='s', color=color)          # Plots the starting community

          # Create legend entry
          legend_label = f"{group_name}: {num_sites} sites, {length:.1f} mi"
          legend_list.append(plt.Line2D([0], [0], color=color, marker='o', linestyle='-', label=legend_label))

      # Add legend to this subplot
      if legend_list:
        ax.legend(handles=legend_list, loc='best', fontsize=8)

      # Set up subplot
      axes[idx].axis('on')  # Turn axis back on
      axes[idx].set_xlabel('Longitude') # X-axis label
      axes[idx].set_ylabel('Latitude') #Y-axis label
      axes[idx].set_xlim(-180,-130)
      axes[idx].set_ylim(50,75)

    # Turn off extra subplots that are not used
    for idx in range(num_regions, len(axes)):
        axes[idx].axis('off')

    plt.tight_layout() # Tight layout
    plt.show() # Show plot



# Setting up TSP Agent

""" Run TSP algorithm on each region separately.
    Parameters:
    - input_dict: nested dictionary of all regions and bulk fuel sites
    - tsp_algo: TSP algorithm to use
    - optimize: whether to optimize the TSP solution
    Returns: {region: RegionalTourResult} """

def run_regional_tsp(input_dict: dict, tsp_algo=greedy_tsp, optimize=True) -> Dict[str, RegionalTourResult]:

    """Run TSP algorithm for each region and delivery method group.
    Returns: Nested dictionary: results[region][delivery_method] = RegionalTourResult"""

    results = {} # Initialize a overall dictionary to store results
    for region in input_dict.keys():
        #print(f"Processing region {region}")

        #Initialize a dictionary to store each RegionalTourResult for each tour in regions
        results[region] = {}

        for dm in input_dict[region].keys():
            #print(f"Processing delivery method {dm} in {region}")
            try:
                # region_cities, delivery_methods, facility_lookup = parse_regional_locations(input_dict, region)
                group_cities, delivery_method_region = parse_regional_locations(input_dict, region, dm)
                if len(group_cities) == 0:
                    print(f"Skipping region {region}: no sites")
                    continue
                t0 = time.perf_counter() # Starts timer
                tour = tsp_algo(group_cities) #Runs TSP algorithm on individual region
                if optimize: # Looks at Optimization functions if optimize=True
                    tour = opt2(tour)
                t1 = time.perf_counter() #Ends timer
                length = tour_length(tour)
                # Result that is put into the result nested dictionary (nested by region and delivery method)
                results[region][dm] = RegionalTourResult(
                    region=region,
                    tour=tour,
                    length= length,
                    secs=t1 - t0,
                    num_sites=len(group_cities))
            except Exception as e:
                print(f"Error processing region {region}: {e}")

    return results

# #Function to convert the RegionalTourResult to a dictionary
# This function treats it as grouped by region ONLY
# def convert_results_for_crewai(results: Dict[str, RegionalTourResult]) -> dict:
#     """Convert RegionalTourResult namedtuples to dictionaries for CrewAI."""
#     converted = {}
    
#     # Check if already converted (all values are dicts, not RegionalTourResult)
#     if results and isinstance(next(iter(results.values())), dict):
#         return results
    
#     for region, result in results.items():
#         converted[region] = {
#             'region': result.region,
#             'tour': [{'longitude': city.real, 'latitude': city.imag} for city in result.tour],  # Convert complex to dict
#             'length': result.length,
#             'secs': result.secs,
#             'num_sites': result.num_sites
#         }
#     return converted

#Function to convert the RegionalTourResult to a dictionary
def convert_results_for_crewai(results: Dict[str, Dict[str, RegionalTourResult]]) -> dict:
    """Convert RegionalTourResult namedtuples to dictionaries for CrewAI.
    
    Input structure: results[region][delivery_method] = RegionalTourResult
    Output structure: Same nested structure but with dicts instead of namedtuples
    """
    converted = {}
    
    for region, delivery_methods in results.items():
        converted[region] = {}
        
        for dm, result in delivery_methods.items():
            # Check if already converted (is a dict, not RegionalTourResult)
            if isinstance(result, dict):
                converted[region][dm] = result
            else:
                # Convert RegionalTourResult to dictionary
                converted[region][dm] = {
                    'region': result.region,
                    'tour': [{'longitude': city.real, 'latitude': city.imag} for city in result.tour],
                    'length': result.length,
                    'secs': result.secs,
                    'num_sites': result.num_sites
                }
    
    return converted


def setup_agents(llm, input_dict, input_report):

    tsp_agent = Agent(
        role = "Route Optimizer and Analyst",
        goal = "Calculate the optimized delivery route and provide insightful analysis considering the Alaskan context.",
        backstory = "Expert in Traveling Salesperson solutions and data analysis, specializing in logistical challenges in remote environments.",
        verbose = True,
        llm = llm,
        tools = []
    )

    # Combined TSP and Interpretation Task
    tsp_task = Task(
        description = f'''Calulate the optimal delivery for {input_dict} using the TSP algorithm.
        The {input_dict} is broken into regions and delivery methods within each region. Each of these groupings should be considered separately.
        Regions include those defined in the {input_dict}.
        After calculating the route, analyze the route data, including the total distance and individual segment distances. Consider the length of the segments that are created and consider the following:
        - Are there more optimal routes?
        - Is there better way to run the functions provided by the TSP?
        - Some groupings do not have a designated delivery method. Try to group these into other groups within the same region, ideally ones that are in close proximity.
        - Provide contextual recommendations considering the challenges of fuel delivery in Alaska, such as limited road access and reliance
        on air and barge transport. Relate the data to real-world scenarios,including logistical challenges and seasonal variations.
        - Finally, plot the data using the {plot_regional_tours} function.
        - Present your analysis and recommendations in a clear text format. Make each segment clear so other agents can analyze''',
        agent = tsp_agent,
        expected_output = "A detailed analysis and recommendations based on the calculated route data."
    )

    #Setting up Cost Estimator Agent
    cost_estimator_agent = Agent(
        role = "Cost Estimator Agent",
        goal = " To assign cost values to each segment of each route in provided by the TSP algorithm",
        backstory = " Energy delivery cost specialist in Alaska.",
        verbose = True,
        llm = llm
    )

    cost_estimation_task = Task(
        description = f"""
        Estimate the cost for each delivery segment provided in the route data from the TSP Agent's findings.

        Consider the following factors in your cost estimation:
        - **Distance:** Longer segments will generally have higher costs. Use the distance information provided for each segment.
        - **Delivery Method:** The cost per mile will vary significantly depending on the delivery method (e.g., road, air, barge). Use the provided delivery method for each segment to make reasonable assumptions based on your knowledge of Alaskan logistics and the locations of the segments.
        - **Fuel Price:** Factor in the current or typical price of fuel in Alaska, as this directly impacts transportation costs. You can assume a general average fuel price or note that the cost is an estimate based on current prices.
        - **Operational Costs:** Include factors like labor, maintenance, and potential infrastructure costs associated with each delivery method.

        Based on these factors, provide a cost estimate for each segment.

        Present your cost estimates in a clear and structured format, listing each segment (perhaps by its start and end points) and its estimated cost. The output should be easily readable and usable by other agents, particularly the Operational Risk Agent.
        """,
        agent = cost_estimator_agent,
        context = [tsp_task],
        expected_output = "A structured list of each segment with its estimated cost, suitable for use by other agents."
    )

    # Setting up Operational Risk Agent
    operational_risk_agent = Agent(
        role = "Operational Risk Agent",
        goal = "Analyze fuel delivery segments from each region in Alaska and its level of risk",
        backstory = "Expert in logistics and market analysis.",
        verbose = True,
        llm = llm
    )

    operational_risk_task = Task(
        description = f""" Assess the risk associated with each fuel delivery segment identified by the TSP Agent within the {input_dict}.
        Use the route data provided by the TSP Agent, which includes details about each segment.
        Also, incorporate the cost information for each segment provided by the Cost Estimator Agent. Lastly, use the {input_report} as your baseline, broadscale analysis to inform your conclusions.

        For each segment, consider the following factors to determine its risk level:
        - **Weather:** Assess the potential impact of weather conditions (e.g., storms, ice, fog) on the feasibility and safety of delivery for that specific segment, considering the typical weather patterns for the region and time of year (if applicable).
        - **Delivery Method:** Evaluate the inherent risks associated with the primary delivery method for that segment (e.g., road conditions for trucks, ice thickness for barges, visibility for air transport).
        - **Cost:** Analyze how the cost of the segment relates to its risk level. Higher costs might indicate more challenging or risky routes (though this is not always the case and should be considered in conjunction with other factors).

        Based on these factors, classify each segment into one of the following risk categories:
        - High risk: Segments with significant potential for delays, accidents, or failure due to weather, delivery method limitations, or other factors.
        - Moderate risk: Segments with some potential risks, but less severe or frequent than high-risk segments.
        - Low risk: Segments with minimal anticipated risks.

        For segments classified as high risk, suggest potential alternative delivery methods or logistical strategies that could mitigate the risk.

        Present your findings in a detailed analysis that clearly identifies each segment, its assessed risk level, the factors contributing to that assessment, and suggested alternatives for high-risk segments. The output should be easily readable and understandable by other agents.
        """,
        agent = operational_risk_agent,
        context = [tsp_task],
        expected_output = "Output a detailed analysis of your findings that can be readable by other agents. This should note the highest risk segments and explanations to back these up."
    )

    #Discussion task between the Operational Risk Agent and Cost Estimator
    operational_cost_method_discussion = Task(
        description = """
        Review the cost estimates provided by the cost estimator agent and factor this into your considerations for operational risk assignments.
        Also, review the delivery method analyst findings about each region and segment of the TSP route.
        Adjust costs of segments with the cost estimator agent as your see fit, once you consider the logistics and risk of each segment.
        Make adjustments to the current suggested delivery methods if two methods were given in the initial data (i.e. select the optimal of the two). """,
        agent = operational_risk_agent,
        expected_output = "An informed cost esitmate for each segment that you can use to complete your overall task of a detiale analysis of risk factors report"
    )

    # Setting up Writing Agent
    writing_agent = Agent(
        role = "Fuel Delivery Analyst and Report Writer",
        goal = "Write an engaging report that includes analysis and provides actionable recommendations for fuel delivery industry leaders in Alaska.",
        backstory = "You are an expert in fuel delivery economics, policy, logistics, and technical writing. You are skilled at analyzing complex information and presenting it in a clear, actionable format.",
        verbose = True,
        llm = llm
    )

    # Multi-Agent Discussion Task
    multi_agent_discussion_task = Task(
        description="""
        The  Operational Risk Agent, Cost Estimator Agent, and you (Fuel Delivery Analyst and Report Writer) will have a discussion to inform the final report.

        * Operational Risk Agent:
            * Share your analysis of the risk associated with each fuel delivery segment.
            * Highlight the segments with the highest risk levels and explain the factors contributing to that assessment (weather, delivery method, cost).
            * Discuss potential alternative delivery methods or logistical strategies that could mitigate risks for high-risk segments.

        * Cost Estimator Agent:
            * Share your cost estimates for each delivery segment.
            * Explain the key factors and assumptions used in your cost estimation process (distance, delivery method assumptions, fuel price, operational costs).
            * Discuss how costs vary across different segments and regions, and what factors drive these variations.

        * You (Fuel Delivery Analyst and Report Writer):
            * Synthesize the information from the Report Analyst, TSP Agent, Operational Risk Agent, and Cost Estimator Agent.
            * Identify the key points that should be included in the final report to provide a comprehensive understanding of the fuel delivery situation in Alaska.
            * Ask clarifying questions to all agents to ensure you have a complete understanding of the logistical challenges, market dynamics, operational risks, and costs, and their interdependencies.
            * For example, ask about:
                * How do market fluctuations impact the cost-benefit and risk analysis of different delivery methods in specific regions?
                * What are the most significant logistical bottlenecks that hinder efficient fuel delivery, and how do they vary across different regions and risk levels?
                * What are the potential synergies or conflicts between different delivery methods, and how can they be optimized to improve overall efficiency and reduce risk and cost?

        The goal of this discussion is to gather specific, actionable insights that will inform the recommendations in the final report.
        """,
        agent = writing_agent,
        expected_output = "A structured summary of the discussion, highlighting key points, added sections, specific examples, and actionable insights from each agent, and identifying what to include in the report."
    )

    # Setting up Contrarian Agent
    contrarian_agent = Agent(
        role = "Supply Chain and Logistics Contrarian",
        goal = "Critically evaluate the analysis and recommendations of other agents, identifying logical inconsistencies and potential oversights from a supply chain and logistics perspective.",
        backstory = "You are a seasoned supply chain and logistics expert with a contrarian mindset. You excel at identifying flaws in reasoning and finding alternative explanations.",
        verbose = True,
        llm = llm
    )

    contrarian_task = Task(
        description = """
        Critically review the comprehensive report and recommendations generated by the tsp_agent, operational_risk_agent, cost_estimator_agent.
        From a supply chain management and logistics perspective, identify:

        1.  Any logical inconsistencies or contradictions in the analysis.
        2.  Potential oversights or missing considerations.
        3.  Alternative explanations or perspectives.
        4.  Any unrealistic or impractical recommendations.
        5.  Areas where the analysis could be strengthened with additional data or insights from supply chain and logistics domain.

        Present your findings in a structured text format, highlighting the specific areas of concern and providing alternative viewpoints or suggestions for improvement.
        Ensure your analysis is grounded in sound supply chain and logistics principles.
        """,
        agent = contrarian_agent,
        expected_output = "A structured text document containing a critical review of the combined_agent's report and recommendations."
    )


    # Create tasks to produce discussion between Contrarian and Writing Agent
    writing_discussion_task_2 = Task(
        description = """
        Review the critique provided by the contrarian_agent in contrarian_task.
        Respond to each point, providing justifications for your analysis and recommendations.
        Address any concerns raised by the contrarian_agent and propose revisions or alternative approaches if necessary.
        """,
        agent = writing_agent,
        expected_output = "A response to the contrarian_agent's critique, with justifications and revisions."
    )

    contrarian_discussion_task_3 = Task(
        description = """
        Review the writing_agent's response.
        Provide any follow-up critiques, or state that the writing_agent has sufficiently addressed the concerns.
        """,
        agent = contrarian_agent,
        expected_output = "Follow-up critiques or confirmation that the writing_agent has addressed concerns."
    )

    # Final Report Task
    writing_task = Task(
        description = """
        Based on the previous discussion with the contrarian_agent, the discussion with the Operational Risk Agent, Cost Estimator Agent, and yourself, and the original analysis, produce a comprehensive document in plain text format that includes:

        1.  An engaging report that synthesizes the information from all relevant agents, highlighting the challenges and opportunities in fuel delivery in Alaska. Use essay-style writing to create a cohesive narrative.
        2.  A section containing clear and actionable recommendations for fuel delivery industry leaders on improving efficiency. These recommendations should be supported by the information presented in the report, especially the delivery method and market considerations.
        3.  Present the recommendations in a structured text format, focusing on key points and practical implementation.
        4.  A section titled "Agent Discussion Summary" that summarizes the key points, specific examples, and actionable insights from the discussion between the Operational Risk Agent, Cost Estimator Agent, and yourself.
        This section should clearly articulate how the discussion informed the final report's analysis and recommendations.
        5.  A section titled "Limitations" that includes a summary the contrarian_agent critiques, including the initial critique, the writing_agent's response, and any follow-up points.
        ***Do not return a JSON format. Return a plain text document.***
        The final output should be a single document in plain text that seamlessly integrates the report, the recommendations, and the contrarian agent's review.
        ***Do not return a JSON format. Return a plain text document.***
        """,
        agent = writing_agent,
        expected_output = "A comprehensive document in plain text containing an engaging report, actionable recommendations, and the contrarian agent's critical review."
    )

    return (tsp_agent, tsp_task, 
        cost_estimator_agent, cost_estimation_task, 
        operational_risk_agent, operational_risk_task, 
        operational_cost_method_discussion, 
        writing_agent, multi_agent_discussion_task,
        contrarian_agent, contrarian_task, 
        writing_discussion_task_2, contrarian_discussion_task_3, 
        writing_task)

# Main Crew set up & main code
def main():
    #Set LLM and API Key
    with open('.env', 'w', encoding='utf-8') as f:
        f.write(f"GEMINI_API_KEY={pipeline.get_api_key()}\n")
        f.write("MODEL=gemini/gemini-2.5-flash-preview-04-17\n")
    
    load_dotenv()
    os.environ["GEMINI_API_KEY"] = pipeline.get_api_key()
    llm = LLM(model='gemini/gemini-2.5-flash')
    
    # Acquire and read in data into a dictionary
    input_dict_path = 'output_regionalization_dictionary.json'  # input dictionary
    input_report_path = 'final_report.json'  # input written broadscale analysis report
    input_dict = pipeline.get_json(input_dict_path)
    input_report = pipeline.get_json(input_report_path)
    
    # Set up Agents - unpack all returned values
    tsp_agent, tsp_task, \
    cost_estimator_agent, cost_estimation_task, \
    operational_risk_agent, operational_risk_task, \
    operational_cost_method_discussion, \
    writing_agent, multi_agent_discussion_task, \
    contrarian_agent, contrarian_task, \
    writing_discussion_task_2, contrarian_discussion_task_3, \
    writing_task = setup_agents(llm, input_dict, input_report)


    # Set up CrewAI
    crew = Crew(
        agents=[tsp_agent, operational_risk_agent, cost_estimator_agent, contrarian_agent, writing_agent],
        tasks=[tsp_task, operational_cost_method_discussion, multi_agent_discussion_task, 
               writing_discussion_task_2, contrarian_discussion_task_3, writing_task],
        process=Process.sequential,
        verbose=True,
        llm=llm
    )
    
    print("Running CrewAI approach...")
    REGION_COLUMN = 'NAME'  # Define REGION_COLUMN
    
    # Run regional TSP calculation using the structured regional dictionary
    regional_results = run_regional_tsp(input_dict, tsp_algo=greedy_tsp, optimize=True)
    
    # Visualize
    plot_regional_tours(input_dict, regional_results)
    
    # Convert named tuples (RegionalTourResult) to a dictionary for CrewAI
    tsp_regional_results_dict = convert_results_for_crewai(regional_results)
    
    # Pass results to CrewAI agents
    result = crew.kickoff(inputs={
        'regional_tsp_results': tsp_regional_results_dict,
        'input_dict': input_dict
    })
    
    print(result)
    with open('tsp_final_report.json', 'w', encoding='utf-8') as f:
        json.dump({"result": str(result)}, f, indent=4)

if __name__ == "__main__":
    main()




